repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    - id: trailing-whitespace
      exclude: \.md$
    - id: end-of-file-fixer
    - id: check-case-conflict
    - id: check-merge-conflict
    - id: check-symlinks
    - id: check-toml
    - id: check-yaml
    - id: mixed-line-ending
    - id: no-commit-to-branch
