# Project information
site_name: BragLog Documentation
site_url: https://greatbahram.github.io/braglog/
site_author: Bahram Aghaei
site_description: >-
  BragLog helps you maintain a record of your professional achievements 🌟

# Repository
repo_name: greatbahram/braglog
repo_url: https://github.com/greatbahram/braglog/

# Copyright
copyright: Copyright &copy; 2025 -  Bahram Aghaei

theme:
  name: material
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/link
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: indigo
      toggle:
        icon: material/toggle-switch-off
        name: Switch to system preference
  features:
    - content.action.edit
    - content.action.view
    - content.code.copy
    - content.tooltips
    - navigation.footer
    - navigation.indexes
    - navigation.sections
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
nav:
  - Overview: index.md
  - Usage: usage.md
  - Exports: export.md
  - Changelog: changelog.md
  - Contributing: contributing.md

plugins:
  - search

markdown_extensions:
  - pymdownx.highlight:
  - pymdownx.snippets

# Additional configuration
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/greatbahram/braglog/
    - icon: fontawesome/brands/python
      link: https://pypi.org/project/braglog/
    - icon: fontawesome/brands/x-twitter
      link: https://x.com/greatbahram
