name: "Run test cases and formatter"
on: [push, pull_request]

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-python@v5
              with:
                python-version-file: ".python-version"
            - uses: astral-sh/setup-uv@v5
            - name: Install dependencies
              run: |
                uv sync --extra dev
            - name: Run tests
              run: |
                uv run pytest .
            - name: Run linter & formatter
              run: |
                ruff check .
                ruff format . --check
